### ISSUE TITLE
Regression - occasional grpc error / code 500 between server and client after v2 switch

### ISSUE THREAD

**Issue by unicell** [micro/examples#116]
**Environment**

- go version go1.13.5 linux/amd64
- ~/gocode/src/github.com/micro/examples$ git describe
v0.2.0-35-g9017cf5
- ~/gocode/src/github.com/micro/go-micro$ git describe
v2.2.0-174-g31c4452f

**Steps to reproduce**

1. MICRO_LOG_LEVEL=debug go run server/main.go
2. MICRO_LOG_LEVEL=debug go run client/main.go
3. Errors on both sides

**Symptoms**

client side errors
```
--- Call example ---
2020-04-02 17:59:29  level=debug [mdns] registry create new service with ip: 10.148.242.116 for: 10.148.242.116
call err:  {"id":"go.micro.client","code":500,"detail":"OK: HTTP status code 200; transport: missing content-type field","status":"Internal Server Error"}
Call: 1 rsp: d2c6f291-b5bf-4db1-9424-563786590563: Hello John
call err:  {"id":"go.micro.client","code":500,"detail":"OK: HTTP status code 200; transport: missing content-type field","status":"Internal Server Error"}
call err:  {"id":"go.micro.client","code":500,"detail":"OK: HTTP status code 200; transport: missing content-type field","status":"Internal Server Error"}
call err:  {"id":"go.micro.client","code":500,"detail":"OK: HTTP status code 200; transport: missing content-type field","status":"Internal Server Error"}
Call: 5 rsp: d2c6f291-b5bf-4db1-9424-563786590563: Hello John
Call: 6 rsp: d2c6f291-b5bf-4db1-9424-563786590563: Hello John
Call: 7 rsp: d2c6f291-b5bf-4db1-9424-563786590563: Hello John
Call: 8 rsp: d2c6f291-b5bf-4db1-9424-563786590563: Hello John
Call: 9 rsp: d2c6f291-b5bf-4db1-9424-563786590563: Hello John
```

server side errors
```
2020-04-02 17:59:22  level=info service=server Subscribing to topic: topic.example
2020-04-02 17:59:22  level=info service=server Subscribing to topic: topic.example
2020-04-02 17:59:29  level=error service=server grpc: received message larger than max (408184937 vs. 4194304)
2020-04-02 17:59:29  level=error service=server grpc: received message larger than max (408184937 vs. 4194304)
2020-04-02 17:59:29.312966 I | Received Example.Call request with metadata: map[:Path:/go.micro.srv.example.Example/Call Content-Type:application/grpc+proto Grpc-Timeout:4998957u Local:[::]:39119 Micro-From-Service:go.micro.server Micro-Span-Id:e7469a1d-01ae-4eed-b9c1-59b704691fc3 Micro-Trace-Id:a3b1a227-adea-42e1-982c-b5c902e70ecd Remote:10.148.242.116:50146 Te:trailers Timeout:5000000000 User-Agent:grpc-go/1.24.0 X-Content-Type:application/grpc+proto X-From-Id:script X-User-Id:john]

...

2020-04-02 17:59:29  level=debug service=server rpc: unable to write error response: EOF

...

2020-04-02 17:59:29.860572 I | Received Example.Call request with metadata: map[:Path:/go.micro.srv.example.Example/Call Content-Type:application/grpc+proto Grpc-Timeout:4999907u Local:[::]:39119 Micro-From-Service:go.micro.server Micro-Span-Id:72493049-85f9-40f3-872e-5ffb3f02facb Micro-Trace-Id:827dcf4f-3c62-4294-b1df-46215f810e04 Remote:10.148.242.116:50170 Te:trailers Timeout:5000000000 User-Agent:grpc-go/1.24.0 X-Content-Type:application/grpc+proto X-From-Id:script X-User-Id:john]
```

**Other Notes**

1. Works well before the v2 switch commit

> commit 9017cf5cd6c005c4d40f5d8e601ebcb53aceb5a9
> Refs: [master], {origin/master}, {origin/HEAD}, v0.2.0-35-g9017cf5
> Author:     Asim Aslam <asim@aslam.me>
> AuthorDate: Wed Apr 1 21:51:40 2020 +0100
> Commit:     Asim Aslam <asim@aslam.me>
> CommitDate: Wed Apr 1 21:51:40 2020 +0100
> 
>     v2

2. Tested another sample project newly generated from `micro new` using github.com/micro/go-micro/v2 v2.4.0 as dependency, and the same style looped service call doesn't problem at all. Most likely cause by some difference between v2 server when used. directly vs using v2 service

**Comment by unicell** [comment]
cc @asim

**Comment by asim** [comment]
Should be resolved with updated versions

**Comment by unicell** [comment]
Still reproducible using the latest 

```
$  go run client/main.go
2020-06-29 15:12:24  file=auth/auth.go:31 level=info Auth [noop] Authenticated as go.micro.server-86801074-523d-4d13-9bd9-4c22d7bacb6d issued by go.micro

--- Call example ---
call err:  {"id":"go.micro.client","code":500,"detail":"OK: HTTP status code 200; transport: missing content-type field","status":"Internal Server Error"}
Call: 1 rsp: e2f8d1be-53c1-4281-b4c6-3051e20b1e89: Hello John
Call: 2 rsp: e2f8d1be-53c1-4281-b4c6-3051e20b1e89: Hello John
Call: 3 rsp: e2f8d1be-53c1-4281-b4c6-3051e20b1e89: Hello John
call err:  {"id":"go.micro.client","code":500,"detail":"OK: HTTP status code 200; transport: missing content-type field","status":"Internal Server Error"}
Call: 5 rsp: e2f8d1be-53c1-4281-b4c6-3051e20b1e89: Hello John
Call: 6 rsp: e2f8d1be-53c1-4281-b4c6-3051e20b1e89: Hello John
Call: 7 rsp: e2f8d1be-53c1-4281-b4c6-3051e20b1e89: Hello John
Call: 8 rsp: e2f8d1be-53c1-4281-b4c6-3051e20b1e89: Hello John
Call: 9 rsp: e2f8d1be-53c1-4281-b4c6-3051e20b1e89: Hello John
```

```
$  git log -1
commit dd9fa5867e9609a96a29dfaf4b9673f0b068f931 (HEAD -> master, origin/master, origin/HEAD)
Author: Ben Toogood <bentoogood@gmail.com>
Date:   Fri Jun 26 14:18:47 2020 +0100

    greeter/srv: fix unused imports
```

@asim Do you mind re-opening the issue?
